[package]
name = "keikan"
version = "0.1.0"
authors = ["Tloru (Isaac C.) <isaacimagine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
